# Generated by Django 4.0.7 on 2022-09-23 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0002_album_owner_photo_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ('title',)},
        ),
        migrations.RemoveField(
            model_name='photo',
            name='link',
        ),
        migrations.AddField(
            model_name='photo',
            name='url',
            field=models.URLField(blank=True, null=True, unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='title',
            field=models.CharField(max_length=40, verbose_name='TITLE'),
        ),
    ]
