# Generated by Django 4.0.7 on 2022-09-23 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0003_alter_photo_options_remove_photo_link_photo_url_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ('id',)},
        ),
    ]
