# Generated by Django 4.0.7 on 2022-09-23 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-id',), 'verbose_name': 'post', 'verbose_name_plural': 'posts'},
        ),
    ]
