# Generated by Django 4.0.7 on 2022-09-27 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0002_bookmark_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='content',
            field=models.TextField(default='내용이 없습니다.', verbose_name='CONTENT'),
        ),
    ]
